# Generated by Django 5.0.3 on 2024-03-06 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollectionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_id', models.CharField(max_length=50, unique=True)),
                ('fill_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pickup_fill_percentage_threshold', models.DecimalField(decimal_places=2, default=80, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Waste Collection Centers',
            },
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('collection_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wastecollectioncenter')),
            ],
        ),
        migrations.CreateModel(
            name='FillPercentageChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('modification_date', models.DateTimeField(auto_now_add=True)),
                ('collection_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wastecollectioncenter')),
            ],
            options={
                'verbose_name_plural': 'Fill Percentage History',
            },
        ),
    ]
