# Generated by Django 5.0.3 on 2024-03-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wastecollectioncenter_pickup_requested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fillpercentagechange',
            options={'ordering': ['modification_date'], 'verbose_name_plural': 'Fill Percentage History'},
        ),
    ]
